jobs:
- job: BuildLinuxWithSonarCloud
  displayName: Build for Linux\CMake With SonarCloud
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'sc-sq-c-family-examples'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'sc-sq-c-family-examples_linux-cmake-azure-sc'
      cliProjectName: 'sc-sq-c-family-examples_linux-cmake-azure-sc'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - bash: |
      mkdir -p $HOME/.sonar
      curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{variables.BUILD_WRAPPER_DOWNLOAD_URL}}
      unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
    displayName: Download and install build wrapper
  - bash: |
      mkdir build
      cmake -S . -B build
      export PATH=$HOME/.sonar/build-wrapper-linux-x86:$PATH
      build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarCloudAnalyze@1
